service: ng-sls-express


provider:
  name: aws
  runtime: nodejs10.x
  stage: dev


functions:
  api:
    handler: lambda.server
    events:
      - http: ANY {proxy+}
      - http: ANY /

package:
  exclude:
   - src/**
   - node_modules/**
   - firebug-lite/**
   - e2e/**
   - coverage/**
   - '!node_modules/aws-serverless-express/**'
   - '!node_modules/express/**'
   - '!node_modules/@vendia/serverless-express/**'
   - '!node_modules/binary-case/**'
   - '!node_modules/type-is/**'
   - '!node_modules/media-typer/**'
   - '!node_modules/mime-types/**'
   - '!node_modules/mime-db/**'

custom:
  apigwBinary:
    types:
      - '*/*'

plugins:
  - serverless-apigw-binary
  - serverless-api-compression
  - serverless-offline
